version: 2
registries:
  maven-repository-wooga-jfrog-io-wooga-atlas-maven:
    type: maven-repository
    url: https://wooga.jfrog.io/wooga/atlas-maven
    username: atlas
    password: "${{secrets.MAVEN_REPOSITORY_WOOGA_JFROG_IO_WOOGA_ATLAS_MAVEN_PASSWORD}}"

updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.codehaus.groovy:groovy-all
    versions:
    - ">= 0"
  - dependency-name: org.spockframework:spock-core
    versions:
    - ">= 0"
  - dependency-name: com.github.kt3k.coveralls
    versions:
    - 2.11.0
  - dependency-name: net.bytebuddy:byte-buddy
    versions:
    - 1.10.20
    - 1.10.21
  registries:
  - maven-repository-wooga-jfrog-io-wooga-atlas-maven
